/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dao.BanDAO;
import dao.HoaDonDAO;
import dto.BanDTO;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrator
 */
public class FrmBan extends javax.swing.JFrame {
    
    private int i;
    private ArrayList<BanDTO> list;
    private DefaultTableModel model;
    private String TT;

    /**
     * Creates new form FrmBan
     */
    public FrmBan() {
        initComponents();
        this.setLocationRelativeTo(this);
        model = (DefaultTableModel) tblTP.getModel();
        list = new BanDAO().readByAll();
        updateTable();
        
    }
    
    public boolean addTP(BanDTO dto) {
        if (txtMaBan.getText().length() == 0 || txtLB.getText().length() == 0) {
            return false;
        }
        dto.setMaBan(txtMaBan.getText());
        dto.setLoaiBan(txtLB.getText());
        String TT = txtTT.getText();
        if (TT.equals("Trống")) {
            dto.setTinhTrang(false);
        } else {
            dto.setTinhTrang(true);
        }
        return true;
    }
    
    public void showList() {
        list = new BanDAO().readByAll();
        for (BanDTO dto : list) {
            if (dto.isTinhTrang()) {
                TT = "Đang phục vụ";
            } else {
                TT = "Trống";
            }
            model.addRow(new Object[]{
                dto.getMaBan(), dto.getLoaiBan(), TT});
        }
        tblTP.updateUI();
    }
    
    public void clearTable() {
        int dong = model.getRowCount();
        for (int j = dong; j > 0; j--) {
            model.removeRow(j - 1);
        }
    }
    
    public void updateTable() {
        clearTable();
        showList();
    }
    
    public void setTextEmpty(String e) {
        txtMaBan.setText("");
        txtLB.setText("");
        txtTT.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblTP = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        txtTK = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cnag = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtMaBan = new javax.swing.JTextField();
        btupd = new javax.swing.JButton();
        btdl = new javax.swing.JButton();
        btcrt = new javax.swing.JButton();
        btxem1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtLB = new javax.swing.JTextField();
        txtTT = new javax.swing.JTextField();

        jToggleButton1.setText("jToggleButton1");

        setTitle("QUẢN LÝ BÀN");
        setResizable(false);

        tblTP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã bàn", "Loại Bàn", "Tình trạng"
            }
        ));
        tblTP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTPMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblTP);

        txtTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTKActionPerformed(evt);
            }
        });
        txtTK.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTKKeyPressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/search.png"))); // NOI18N
        jLabel2.setText("Tìm kiếm");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(txtTK, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        cnag.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "QUẢN LÝ BÀN ĂN", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(255, 0, 51))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/flag.png"))); // NOI18N
        jLabel6.setText(" Mã Bàn");

        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/flag.png"))); // NOI18N
        jLabel7.setText(" Loại Bàn");

        txtMaBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaBanActionPerformed(evt);
            }
        });

        btupd.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        btupd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icon.png"))); // NOI18N
        btupd.setText("Cập nhật");
        btupd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btupdActionPerformed(evt);
            }
        });

        btdl.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        btdl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/delete (1).png"))); // NOI18N
        btdl.setText("Xóa");
        btdl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btdlActionPerformed(evt);
            }
        });

        btcrt.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        btcrt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/plus.png"))); // NOI18N
        btcrt.setText("Thêm mới");
        btcrt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcrtActionPerformed(evt);
            }
        });

        btxem1.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        btxem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/exchange.png"))); // NOI18N
        btxem1.setText("Clear");
        btxem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btxem1ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/flag.png"))); // NOI18N
        jLabel8.setText(" Tình trạng");

        txtLB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLBActionPerformed(evt);
            }
        });

        txtTT.setEnabled(false);

        javax.swing.GroupLayout cnagLayout = new javax.swing.GroupLayout(cnag);
        cnag.setLayout(cnagLayout);
        cnagLayout.setHorizontalGroup(
            cnagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cnagLayout.createSequentialGroup()
                .addComponent(btcrt)
                .addGap(18, 18, 18)
                .addComponent(btdl, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(btupd, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btxem1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cnagLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(cnagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68)
                .addGroup(cnagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMaBan, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLB, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                    .addComponent(txtTT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(92, 92, 92))
        );

        cnagLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtLB, txtMaBan, txtTT});

        cnagLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btcrt, btdl, btupd, btxem1});

        cnagLayout.setVerticalGroup(
            cnagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cnagLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(cnagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cnagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(cnagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72)
                .addGroup(cnagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btcrt)
                    .addComponent(btdl)
                    .addComponent(btupd, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btxem1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cnagLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel6, jLabel7, jLabel8});

        cnagLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btcrt, btdl, btupd, btxem1});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(cnag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cnag, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblTPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTPMouseClicked
        i = tblTP.getSelectedRow();
        txtMaBan.setText("" + tblTP.getValueAt(i, 0));
        txtLB.setText("" + tblTP.getValueAt(i, 1));
        txtTT.setText(""+tblTP.getValueAt(i, 2));
    }//GEN-LAST:event_tblTPMouseClicked

    private void txtTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTKActionPerformed
        list = new BanDAO().readByName(txtTK.getText());
        clearTable();
        for (BanDTO dto : list) {
            model.addRow(new Object[]{
                dto.getMaBan(), dto.getLoaiBan(), "" + dto.isTinhTrang()});
        }
    }//GEN-LAST:event_txtTKActionPerformed

    private void btxem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btxem1ActionPerformed
        setTextEmpty("");
    }//GEN-LAST:event_btxem1ActionPerformed

    private void btcrtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcrtActionPerformed
        BanDTO dto = new BanDTO();
        if (addTP(dto)) {
            BanDAO dao = new BanDAO();
            if (dao.checkMaBan(dto)) {
                JOptionPane.showMessageDialog(null, "Mã bàn đã tồn tại");
                txtMaBan.requestFocus();
                return;
            }
            if (JOptionPane.showConfirmDialog(null, "Bạn chắc chắn thêm", "Thông báo", 2) == 0) {
                if (dao.create(dto)) {
                    list = dao.readByAll();
                    for (int j = 0; j < list.size(); j++) {
                        if (dto.getMaBan().equals(this.list.get(j).getMaBan())) {
                            i = j;
                        }
                    }
                    updateTable();
                    tblTP.setRowSelectionInterval(i, i);
                    setTextEmpty("");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Thêm không thành công");
            }
            
        } else {
            JOptionPane.showMessageDialog(null, "Bạn không được để trống");
        }
    }//GEN-LAST:event_btcrtActionPerformed

    private void btdlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btdlActionPerformed
        BanDAO dao = new BanDAO();
        BanDTO dto = new BanDTO();
        dto.setMaBan(txtMaBan.getText());
        if (JOptionPane.showConfirmDialog(null, "bạn chắc chắn xóa", "Thông báo", 2) == 0) {
            if (new HoaDonDAO().updateBan(dto.getMaBan())) {
                if (dao.delete(dto)) {
                    setTextEmpty("");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Mã bàn không tồn tại");
                txtMaBan.requestFocus();
                return;
            }
        }
        updateTable();
    }//GEN-LAST:event_btdlActionPerformed

    private void btupdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btupdActionPerformed
        BanDTO dto = new BanDTO();
        if (addTP(dto)) {
            BanDAO dao = new BanDAO();
            if (!dao.checkMaBan(dto)) {
                JOptionPane.showMessageDialog(null, "Mã bàn không tồn tại");
                txtMaBan.requestFocus();
                return;
            }
            if (JOptionPane.showConfirmDialog(null, "Bạn chắc chắn cập nhật lại", "Thông báo", 2) == 0) {
                if (dao.update(dto)) {
                    setTextEmpty("");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Cập nhật không thành công");
            }
            updateTable();
            tblTP.setRowSelectionInterval(i, i);
        } else {
            JOptionPane.showMessageDialog(null, "Bạn không được để trống ");
        }
    }//GEN-LAST:event_btupdActionPerformed

    private void txtMaBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaBanActionPerformed

    }//GEN-LAST:event_txtMaBanActionPerformed

    private void txtLBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLBActionPerformed

    private void txtTKKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTKKeyPressed
        list = new BanDAO().readByName(txtTK.getText());
        clearTable();
        for (BanDTO dto : list) {
            model.addRow(new Object[]{
                dto.getMaBan(), dto.getLoaiBan(), "" + dto.isTinhTrang()});
        }
    }//GEN-LAST:event_txtTKKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmBan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmBan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmBan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmBan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmBan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btcrt;
    private javax.swing.JButton btdl;
    private javax.swing.JButton btupd;
    private javax.swing.JButton btxem1;
    private javax.swing.JPanel cnag;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTable tblTP;
    private javax.swing.JTextField txtLB;
    private javax.swing.JTextField txtMaBan;
    private javax.swing.JTextField txtTK;
    private javax.swing.JTextField txtTT;
    // End of variables declaration//GEN-END:variables
}
