/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dao.LoaiThucPhamDAO;
import dto.LoaiThucPhamDTO;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrator
 */
public class FrmLtp extends javax.swing.JFrame {

    /**
     * Creates new form LoaiThucPham
     */
    private int i = 0;
    private ArrayList<LoaiThucPhamDTO> list;
    private DefaultTableModel model;

    public FrmLtp() {
        initComponents();
        this.setLocationRelativeTo(this);
        model = (DefaultTableModel) tblTP.getModel();
        updateTable();
    }

    public void showlist() {
        list = new LoaiThucPhamDAO().readByALL();
        for (LoaiThucPhamDTO dto : list) {
            model.addRow(new Object[]{
                dto.getMaLTP(), dto.getTenLTP()
            });
        }
        tblTP.updateUI();
    }

    public void clearTable() {
        int dong = model.getRowCount();
        for (int i = dong; i > 0; i--) {
            model.removeRow(i - 1);
        }
    }

    public void updateTable() {
        clearTable();
        showlist();
    }

    public void setTextEmpty(String e) {
        txtMaLTP.setText(e);
        txtTenLTP.setText(e);
    }

    public boolean addLTP(LoaiThucPhamDTO dto) {
        if (txtTenLTP.getText().length() == 0 || txtMaLTP.getText().length() == 0) {
            return false;
        }
        dto.setMaLTP(txtMaLTP.getText());
        dto.setTenLTP(txtTenLTP.getText());
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblTP = new javax.swing.JTable();
        cnag = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtMaLTP = new javax.swing.JTextField();
        btupd = new javax.swing.JButton();
        btdl = new javax.swing.JButton();
        btcrt = new javax.swing.JButton();
        btxem1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtTenLTP = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtTK = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        setResizable(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 44, Short.MAX_VALUE)
        );

        tblTP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã loại thực phẩm", "Tên loại thực phẩm"
            }
        ));
        tblTP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTPMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblTP);

        cnag.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "QUẢN LÝ LOẠI THỰC PHẨM", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(255, 0, 51))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/food.png"))); // NOI18N
        jLabel6.setText("Mã loại thực phẩm");

        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/food.png"))); // NOI18N
        jLabel7.setText("Tên loại thực phẩm");

        txtMaLTP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaLTPActionPerformed(evt);
            }
        });

        btupd.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btupd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icon.png"))); // NOI18N
        btupd.setText("Cập nhật");
        btupd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btupdActionPerformed(evt);
            }
        });

        btdl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btdl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/delete (1).png"))); // NOI18N
        btdl.setText("Xóa");
        btdl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btdlActionPerformed(evt);
            }
        });

        btcrt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btcrt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/plus.png"))); // NOI18N
        btcrt.setText("Thêm LTP");
        btcrt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcrtActionPerformed(evt);
            }
        });

        btxem1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btxem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/exchange (1).png"))); // NOI18N
        btxem1.setText("Nhập lại");
        btxem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btxem1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));

        txtTenLTP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenLTPActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel11.setText("***");

        jLabel12.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel12.setText("***");

        jLabel8.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel8.setText("*** Lưu ý: Không được để trống");

        javax.swing.GroupLayout cnagLayout = new javax.swing.GroupLayout(cnag);
        cnag.setLayout(cnagLayout);
        cnagLayout.setHorizontalGroup(
            cnagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cnagLayout.createSequentialGroup()
                .addGroup(cnagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(cnagLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(btcrt, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btupd, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btdl, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btxem1))
                    .addGroup(cnagLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(cnagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(cnagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(cnagLayout.createSequentialGroup()
                                .addComponent(txtMaLTP, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(cnagLayout.createSequentialGroup()
                                .addComponent(txtTenLTP, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cnagLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btcrt, btdl, btupd, btxem1});

        cnagLayout.setVerticalGroup(
            cnagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cnagLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGroup(cnagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cnagLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(cnagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(txtTenLTP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(cnagLayout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addGroup(cnagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMaLTP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jLabel8)
                .addGap(45, 45, 45)
                .addGroup(cnagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btxem1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btdl, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btupd, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btcrt, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(110, 110, 110))
        );

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Search.png"))); // NOI18N
        jLabel2.setText("Tìm kiếm");

        txtTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTKActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel10.setText("***");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(cnag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTK, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 9, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(477, 477, 477)
                    .addComponent(jLabel10)
                    .addContainerGap(488, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(14, Short.MAX_VALUE)
                        .addComponent(cnag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtTK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(224, 224, 224)
                    .addComponent(jLabel10)
                    .addContainerGap(225, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTKActionPerformed
        list = new LoaiThucPhamDAO().readByName(txtTK.getText());
        clearTable();
        for (LoaiThucPhamDTO dto : list) {
            model.addRow(new Object[]{
                dto.getMaLTP(), dto.getTenLTP()
            });
        }
    }//GEN-LAST:event_txtTKActionPerformed

    private void tblTPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTPMouseClicked
        i = tblTP.getSelectedRow();
        txtMaLTP.setText("" + tblTP.getValueAt(i, 0));
        txtTenLTP.setText("" + tblTP.getValueAt(i, 1));
    }//GEN-LAST:event_tblTPMouseClicked

    private void btxem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btxem1ActionPerformed
        setTextEmpty("");
    }//GEN-LAST:event_btxem1ActionPerformed

    private void btcrtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcrtActionPerformed
        LoaiThucPhamDAO dao = new LoaiThucPhamDAO();
        LoaiThucPhamDTO dto = new LoaiThucPhamDTO();
        if (addLTP(dto)) {
            if (new LoaiThucPhamDAO().checkMaLTP(dto)) {
                JOptionPane.showMessageDialog(null, "Mã loại TP đã tồn tại");
                txtMaLTP.requestFocus();
            } else if (JOptionPane.showConfirmDialog(null, "Bạn chắc chắn thêm", "Thông báo", 2) == 0) {
                if (dao.create(dto)) {
                    list = dao.readByALL();
                    int vt = 0;
                    for (int j = 0; j < list.size(); j++) {
                        if (dto.getMaLTP().equals(list.get(j).getMaLTP())) {
                            vt = j;
                        }
                    }
                    updateTable();
                    setTextEmpty("");
                    tblTP.setRowSelectionInterval(vt, vt);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Thêm không thành công");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Bạn không được để trống");
        }
    }//GEN-LAST:event_btcrtActionPerformed

    private void btdlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btdlActionPerformed
        LoaiThucPhamDAO dao = new LoaiThucPhamDAO();
        LoaiThucPhamDTO dto = new LoaiThucPhamDTO();
        dto.setMaLTP(txtMaLTP.getText());
        if (JOptionPane.showConfirmDialog(null, "Bạn chắc chắn xóa", "Thông báo", 2) == 0) {
            if (new LoaiThucPhamDAO().checkMaLTP(dto)) {
                if (dao.delete(dto)) {
                    setTextEmpty("");
                } else {
                    JOptionPane.showMessageDialog(null, dao.mess);
                    return;
                }
            } else {
                JOptionPane.showMessageDialog(null, "Mã loại thực phẩm không tồn tại");
                txtMaLTP.requestFocus();
                return;
            }
        }
        updateTable();
    }//GEN-LAST:event_btdlActionPerformed

    private void btupdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btupdActionPerformed
        LoaiThucPhamDAO dao = new LoaiThucPhamDAO();
        LoaiThucPhamDTO dto = new LoaiThucPhamDTO();
        if (addLTP(dto)) {
            if (!dao.checkMaLTP(dto)) {
                JOptionPane.showMessageDialog(null, "Mã loại thực phẩm không tồn tại");
                txtMaLTP.requestFocus();
                return;
            }
            if (JOptionPane.showConfirmDialog(null, "Bạn chắc chắn cập nhật lại", "Thông báo", 2) == 0) {
                if (dao.update(dto)) {
                    setTextEmpty("");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Cập nhật không thành công");
            }
            updateTable();
            tblTP.setRowSelectionInterval(i, i);
        } else {
            JOptionPane.showMessageDialog(null, "Bạn không được để trống");
        }
    }//GEN-LAST:event_btupdActionPerformed

    private void txtMaLTPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaLTPActionPerformed

    }//GEN-LAST:event_txtMaLTPActionPerformed

    private void txtTenLTPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenLTPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenLTPActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmLtp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmLtp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmLtp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmLtp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmLtp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btcrt;
    private javax.swing.JButton btdl;
    private javax.swing.JButton btupd;
    private javax.swing.JButton btxem1;
    private javax.swing.JPanel cnag;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblTP;
    private javax.swing.JTextField txtMaLTP;
    private javax.swing.JTextField txtTK;
    private javax.swing.JTextField txtTenLTP;
    // End of variables declaration//GEN-END:variables
}
