/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dao.LoaiThucPhamDAO;
import dao.ThucPhamDAO;
import dto.ThucPhamDTO;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrator
 */
public class FrmThucPham extends javax.swing.JFrame {

    private int i;
    private ArrayList<ThucPhamDTO> list = new ArrayList<ThucPhamDTO>();
    private DefaultTableModel model;
    private String LTP;

    /**
     * Creates new form QUANLYTHUCPHAM
     */
    public FrmThucPham() {
        initComponents();
        setLocationRelativeTo(this);
        model = (DefaultTableModel) tblTP.getModel();
        ArrayList<String> list1 = new LoaiThucPhamDAO().readTenLTP();
        for (String s : list1) {
            cbMLTP.addItem(s);
            cbLTP1.addItem(s);
        }
        cbLTP1.addItem("Toàn bộ");
        updateTable();
    }

    public void settbTP(ArrayList<ThucPhamDTO> list) {
        for (ThucPhamDTO dto : list) {
            model.addRow(new Object[]{
                dto.getTenTP(), dto.getDonvt(), (int) dto.getGia()});
        }
        tblTP.updateUI();
    }

    public boolean addTP(ThucPhamDTO dto) {
        if (txtMaTP.getText().length() == 0 || txtTenTP.getText().length() == 0 || txtGia.getText().length() == 0) {
            return false;
        }
        try {
            dto.setGia(Integer.parseInt(txtGia.getText()));
        } catch (NumberFormatException e) {
            return false;
        }
        dto.setMaTP(txtMaTP.getText());
        dto.setTenTP(txtTenTP.getText());
        String TenLTP = new String(cbMLTP.getSelectedItem().toString());
        String MaLTP = new LoaiThucPhamDAO().readMaLTP(TenLTP);
        dto.setMaLTP(MaLTP);
        String Donvt = "" + cbDvt.getSelectedItem();
        dto.setDonvt(Donvt);
        return true;
    }

    public void showList() {
        for (ThucPhamDTO dto : list) {
            model.addRow(new Object[]{
                dto.getMaTP(), dto.getTenTP(), dto.getMaLTP(), (int) dto.getGia(), dto.getDonvt()});
        }
        tblTP.updateUI();
    }

    public void clearTable() {
        int dong = model.getRowCount();
        for (int a = dong; a > 0; a--) {
            model.removeRow(a - 1);
        }
    }

    public void updateTable() {
        clearTable();
        showList();
    }

    public void setTextEmpty(String e) {
        cbDvt.setSelectedIndex(0);
        txtGia.setText(e);
        txtMaTP.setText(e);
        txtTenTP.setText(e);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        txtTK = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cbLTP1 = new javax.swing.JComboBox<>();
        cnag = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtMaTP = new javax.swing.JTextField();
        txtGia = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtTenTP = new javax.swing.JTextField();
        btupd = new javax.swing.JButton();
        btdl = new javax.swing.JButton();
        btcrt = new javax.swing.JButton();
        btxem1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        cbMLTP = new javax.swing.JComboBox<>();
        cbDvt = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblTP = new javax.swing.JTable();

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable2);

        setTitle("QUẢN LÝ THỰC PHẨM");
        setResizable(false);

        txtTK.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        txtTK.setText("         (Nhập tên cần tìm kiếm)");
        txtTK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtTKMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtTKMouseEntered(evt);
            }
        });
        txtTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTKActionPerformed(evt);
            }
        });
        txtTK.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTKKeyPressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Search.png"))); // NOI18N
        jLabel6.setText("Tìm kiếm");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/food.png"))); // NOI18N
        jLabel12.setText("Loại TP");

        cbLTP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbLTP1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtTK, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                    .addComponent(cbLTP1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(146, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtTK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(cbLTP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        cnag.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "QUẢN LÝ THỰC PHẨM", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(255, 0, 102))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/food.png"))); // NOI18N
        jLabel7.setText(" Loại thực phẩm");

        jLabel8.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/food.png"))); // NOI18N
        jLabel8.setText("Giá");

        jLabel9.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/food.png"))); // NOI18N
        jLabel9.setText("Đơn vị tính");

        txtMaTP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaTPActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/food.png"))); // NOI18N
        jLabel10.setText("Tên thực phẩm");

        txtTenTP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenTPActionPerformed(evt);
            }
        });

        btupd.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        btupd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icon.png"))); // NOI18N
        btupd.setText("Cập nhật");
        btupd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btupdActionPerformed(evt);
            }
        });

        btdl.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        btdl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/delete (1).png"))); // NOI18N
        btdl.setText("Xóa");
        btdl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btdlActionPerformed(evt);
            }
        });

        btcrt.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        btcrt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/plus.png"))); // NOI18N
        btcrt.setText("Thêm TP");
        btcrt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcrtActionPerformed(evt);
            }
        });

        btxem1.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        btxem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/exchange (1).png"))); // NOI18N
        btxem1.setText("Nhập lại");
        btxem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btxem1ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/food.png"))); // NOI18N
        jLabel11.setText("Mã thực phẩm");

        cbMLTP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMLTPActionPerformed(evt);
            }
        });

        cbDvt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "dĩa", "phần", "tô", "lon", "chai", "ly" }));
        cbDvt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDvtActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel13.setText("*** Lưu ý: Không được để trống");

        jLabel14.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel14.setText("***");

        jLabel15.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel15.setText("***");

        jLabel16.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel16.setText("***");

        javax.swing.GroupLayout cnagLayout = new javax.swing.GroupLayout(cnag);
        cnag.setLayout(cnagLayout);
        cnagLayout.setHorizontalGroup(
            cnagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cnagLayout.createSequentialGroup()
                .addGroup(cnagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cnagLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btcrt)
                        .addGap(8, 8, 8)
                        .addComponent(btdl, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(btupd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btxem1))
                    .addGroup(cnagLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(cnagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, cnagLayout.createSequentialGroup()
                                .addGroup(cnagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(41, 41, 41)
                                .addGroup(cnagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbDvt, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(cnagLayout.createSequentialGroup()
                                        .addComponent(txtGia)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, cnagLayout.createSequentialGroup()
                                .addGroup(cnagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(41, 41, 41)
                                .addGroup(cnagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(cnagLayout.createSequentialGroup()
                                        .addComponent(txtMaTP, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(cnagLayout.createSequentialGroup()
                                        .addComponent(txtTenTP, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(cbMLTP, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cnagLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cbDvt, cbMLTP, txtGia, txtMaTP, txtTenTP});

        cnagLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel10, jLabel11, jLabel7, jLabel8, jLabel9});

        cnagLayout.setVerticalGroup(
            cnagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cnagLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(cnagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaTP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel15))
                .addGap(25, 25, 25)
                .addGroup(cnagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTenTP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(27, 27, 27)
                .addGroup(cnagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbMLTP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(cnagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(cnagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel14)
                        .addComponent(txtGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addGroup(cnagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cbDvt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jLabel13)
                .addGap(34, 34, 34)
                .addGroup(cnagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btcrt, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btdl, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btupd, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btxem1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cnagLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cbDvt, cbMLTP, txtGia, txtMaTP, txtTenTP});

        cnagLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel10, jLabel11, jLabel7, jLabel8, jLabel9});

        tblTP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã TP", "Tên TP", "Nhóm TP", "Giá", "Đơn vị tính"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblTP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTPMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblTP);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(cnag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cnag, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTKActionPerformed
        String s = "" + cbLTP1.getSelectedItem();
        String MaLTP = new LoaiThucPhamDAO().readMaLTP(s);
        list = new ThucPhamDAO().tkRieng(txtTK.getText(), MaLTP);
        clearTable();
        showList();
    }//GEN-LAST:event_txtTKActionPerformed

    private void btdlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btdlActionPerformed
        ThucPhamDAO dao = new ThucPhamDAO();
        ThucPhamDTO dto = new ThucPhamDTO();
        dto.setMaTP(txtMaTP.getText());
        dto.setMaLTP(LTP);
        if (JOptionPane.showConfirmDialog(null, "bạn chắc chắn xóa", "Thông báo", 2) == 0) {
            if (dao.delete(dto)) {
                setTextEmpty("");
                String MaLTP = "" + cbMLTP.getSelectedItem().toString();
                cbLTP1.setSelectedItem("" + MaLTP);
                list = new ThucPhamDAO().readAllName(MaLTP);
                updateTable();
            } else {
                JOptionPane.showMessageDialog(null, "Mã TP không tồn tại");
                txtMaTP.requestFocus();
                return;
            }
        }
    }//GEN-LAST:event_btdlActionPerformed

    private void btcrtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcrtActionPerformed
        ThucPhamDTO dto = new ThucPhamDTO();
        if (addTP(dto)) {
            ThucPhamDAO dao = new ThucPhamDAO();
            if (dao.checkMaTP(dto)) {
                JOptionPane.showMessageDialog(null, "Mã TP đã tồn tại");
                txtMaTP.requestFocus();
                return;
            }
            if (JOptionPane.showConfirmDialog(null, "Bạn chắc chắn thêm", "Thông báo", 2) == 0) {
                if (dao.create(dto)) {
//                    list = dao.readByAll();
////                    setTextEmpty("");
////                    clearTable();
                    String MaLTP = "" + cbMLTP.getSelectedItem().toString();
                    cbLTP1.setSelectedItem("" + MaLTP);
                    list = new ThucPhamDAO().readAllName(MaLTP);
                    showList();
                    for (int j = 0; j < list.size(); j++) {
                        if (dto.getMaTP().equals(this.list.get(j).getMaTP())) {
                            i = j;
                        }
                    }
                    updateTable();
                    setTextEmpty("");
                    tblTP.setRowSelectionInterval(i, i);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Thêm không thành công");
            }

        } else {
            JOptionPane.showMessageDialog(null, "Bạn đã để trống ô hoặc nhập sai giá");
        }
    }//GEN-LAST:event_btcrtActionPerformed

    private void txtMaTPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaTPActionPerformed

    }//GEN-LAST:event_txtMaTPActionPerformed

    private void btupdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btupdActionPerformed
        ThucPhamDTO dto = new ThucPhamDTO();
        if (addTP(dto)) {
            ThucPhamDAO dao = new ThucPhamDAO();
            if (!dao.checkMaTP(dto)) {
                JOptionPane.showMessageDialog(null, "Mã TP không tồn tại");
                txtMaTP.requestFocus();
                return;
            }
            if (JOptionPane.showConfirmDialog(null, "bạn chắc chắn cập nhật lại", "Thông báo", 2) == 0) {
                if (dao.update(dto)) {
                    String MaLTP = "" + cbMLTP.getSelectedItem().toString();
                    cbLTP1.setSelectedItem("" + MaLTP);
                    list = new ThucPhamDAO().readAllName(MaLTP);
                    showList();
                    for (int j = 0; j < list.size(); j++) {
                        if (dto.getMaTP().equals(this.list.get(j).getMaTP())) {
                            i = j;
                        }
                    }
                    updateTable();
                    setTextEmpty("");
                    tblTP.setRowSelectionInterval(i, i);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Cập nhật không thành công");
            }
            updateTable();
            tblTP.setRowSelectionInterval(i, i);
        } else {
            JOptionPane.showMessageDialog(null, "Bạn đã để trống ô hoặc nhập sai giá");
        }
    }//GEN-LAST:event_btupdActionPerformed

    private void txtTenTPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenTPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenTPActionPerformed

    private void tblTPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTPMouseClicked
        i = tblTP.getSelectedRow();
        txtMaTP.setText("" + tblTP.getValueAt(i, 0));
        txtTenTP.setText("" + tblTP.getValueAt(i, 1));
        txtGia.setText("" + tblTP.getValueAt(i, 3));
        String row = "" + tblTP.getValueAt(i, 2);
        LTP= "" + tblTP.getValueAt(i, 2);
        ArrayList<String> list1 = new LoaiThucPhamDAO().readMTLP();
        for (int j = 0; j < list1.size(); j++) {
            if (row.equals(list1.get(j))) {
                cbMLTP.setSelectedIndex(j);
            }
        }
        cbDvt.setSelectedItem("" + tblTP.getValueAt(i, 4));
    }//GEN-LAST:event_tblTPMouseClicked

    private void btxem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btxem1ActionPerformed
        setTextEmpty("");
        cbMLTP.setSelectedIndex(0);
    }//GEN-LAST:event_btxem1ActionPerformed

    private void txtTKMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTKMouseEntered

    }//GEN-LAST:event_txtTKMouseEntered

    private void cbMLTPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMLTPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMLTPActionPerformed

    private void cbDvtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbDvtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbDvtActionPerformed

    private void cbLTP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbLTP1ActionPerformed
        String MaLTP = "" + cbLTP1.getSelectedItem().toString();
        clearTable();
        if (MaLTP.equals("Toàn bộ")) {
            list = new ThucPhamDAO().readByAll();
        } else {
            list = new ThucPhamDAO().readAllName(MaLTP);
        }
        clearTable();
        showList();
    }//GEN-LAST:event_cbLTP1ActionPerformed

    private void txtTKKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTKKeyPressed
        String s = "" + cbLTP1.getSelectedItem();
        if (s.equals("Toàn bộ")) {
            list = new ThucPhamDAO().readByName(txtTK.getText());
            clearTable();
            showList();
        } else {
            String MaLTP = new LoaiThucPhamDAO().readMaLTP(s);
            list = new ThucPhamDAO().tkRieng(txtTK.getText(), MaLTP);
            clearTable();
            showList();
        }
    }//GEN-LAST:event_txtTKKeyPressed

    private void txtTKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTKMouseClicked
        txtTK.setText("");
    }//GEN-LAST:event_txtTKMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmThucPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmThucPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmThucPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmThucPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmThucPham().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btcrt;
    private javax.swing.JButton btdl;
    private javax.swing.JButton btupd;
    private javax.swing.JButton btxem1;
    private javax.swing.JComboBox<String> cbDvt;
    private javax.swing.JComboBox<String> cbLTP1;
    private javax.swing.JComboBox<String> cbMLTP;
    private javax.swing.JPanel cnag;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable tblTP;
    private javax.swing.JTextField txtGia;
    private javax.swing.JTextField txtMaTP;
    private javax.swing.JTextField txtTK;
    private javax.swing.JTextField txtTenTP;
    // End of variables declaration//GEN-END:variables
}
